<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/es/default.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.4 stable 
 * Spanisch translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Klaus Bogotz (klabog) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['ch_flowplayer']['0'] = "Videos / Listas reproductoras";
$GLOBALS['TL_LANG']['MOD']['ch_flowplayer']['1'] = "Administrar vídeos y listas reproductoras";
$GLOBALS['TL_LANG']['CTE']['ch_flowplayer']['0'] = "Vídeo";
$GLOBALS['TL_LANG']['CTE']['ch_flowplayer']['1'] = "Reproducir un vídeo";
$GLOBALS['TL_LANG']['ch_flowplayer']['error'] = "Vídeo no encontrado.";
 
?>
