<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/es/modules.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.4 stable 
 * Spanisch translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Klaus Bogotz (klabog) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['ch_flowplayer_reader']['0'] = "Lector de Flowplayer";
$GLOBALS['TL_LANG']['FMD']['ch_flowplayer_reader']['1'] = "incrusta un objeto de Flowplayer que está unido a una lista reproductora";
$GLOBALS['TL_LANG']['FMD']['ch_flowplayer_list']['0'] = "Lista de Flowplayer";
$GLOBALS['TL_LANG']['FMD']['ch_flowplayer_list']['1'] = "genera una lista de vídeos de una lista reproductora";
 
?>
