<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/es/tl_ch_flowplayer_playlist.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.4 stable 
 * Spanisch translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Klaus Bogotz (klabog) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['title']['0'] = "Titulo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['title']['1'] = "Titulo del vídeo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['alias']['0'] = "Alias del vídeo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['alias']['1'] = "El alias del vídeo es la única referencia que puede ser llamada a parte del ID numérico del vídeo.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['description']['0'] = "Descripción";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['description']['1'] = "Más detalles del vídeo.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['movie']['0'] = "Fichero fuente";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['movie']['1'] = "Seleccióna un fichero FLV, MP4 o SWF";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['preview']['0'] = "Vista previa";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['preview']['1'] = "Imagen para el avance de la película. Por favor elige un fichero JPG o PNG.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['params']['0'] = "Parámetro";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['params']['1'] = "Parámetros acuerde a flowplayer.org que serán unicamente aplicados a este vídeo. Introduciendo parámetros sobrescribe todos los ajustes y definiciones anteriores como reproducción automática. Puedes añadirlos manualmente aquí.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['published']['0'] = "Publicado";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['published']['1'] = "Este vídeo está publicado.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['addImage']['0'] = "Añade una imagen";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['addImage']['1'] = "Añade una imagen a este vídeo.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['new']['0'] = "Vídeo nuevo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['new']['1'] = "Crea un nuevo vídeo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['edit']['0'] = "Edita el vídeo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['edit']['1'] = "Edita el vídeo ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['copy']['0'] = "Duplica el vídeo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['copy']['1'] = "Duplica el vídeo ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['delete']['0'] = "Borra el vídeo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['delete']['1'] = "Borra el vídeo ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['show']['0'] = "Detalles del vídeo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['show']['1'] = "Detalles del vídeo ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['title_legend'] = "Titulo y alias";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['movie_legend'] = "Ajustes del vídeo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['params_legend'] = "Ajustes de los parámetros";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['publish_legend'] = "Publicación";
$GLOBALS['TL_LANG']['tl_style']['cut']['0'] = "Mueve el vídeo";
$GLOBALS['TL_LANG']['tl_style']['cut']['1'] = "Mueve el vídeo ID %s";
$GLOBALS['TL_LANG']['tl_style']['pasteafter']['0'] = "Pega arriba";
$GLOBALS['TL_LANG']['tl_style']['pasteafter']['1'] = "Pega después del vídeo ID %s";
$GLOBALS['TL_LANG']['tl_style']['pastenew']['0'] = "Añade nuevo arriba";
$GLOBALS['TL_LANG']['tl_style']['pastenew']['1'] = "Añade nuevo después del vídeo %s";
 
?>
