<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/es/tl_content.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.4 stable 
 * Spanisch translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Klaus Bogotz (klabog) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['ch_params']['0'] = "Parámetro";
$GLOBALS['TL_LANG']['tl_content']['ch_params']['1'] = "Parámetros acuerde a flowplayer.org que serán unicamente aplicados a este vídeo. Introduciendo parámetros sobrescribe todos los ajustes y definiciones anteriores como reproducción";
$GLOBALS['TL_LANG']['tl_content']['ch_movie']['0'] = "Fichero fuente";
$GLOBALS['TL_LANG']['tl_content']['ch_movie']['1'] = "Seleccióna un fichero FLV, MP4 o SWF";
$GLOBALS['TL_LANG']['tl_content']['ch_playersize']['0'] = "Anchura y altura";
$GLOBALS['TL_LANG']['tl_content']['ch_playersize']['1'] = "Anchura y altura del reproductor.";
$GLOBALS['TL_LANG']['tl_content']['ch_description']['0'] = "Descripción";
$GLOBALS['TL_LANG']['tl_content']['ch_description']['1'] = "Más detalles del vídeo";
$GLOBALS['TL_LANG']['tl_content']['ch_autoplay']['0'] = "Reproducción automática";
$GLOBALS['TL_LANG']['tl_content']['ch_autoplay']['1'] = "Arranca el vídeo automáticamente cuando la página se carga";
$GLOBALS['TL_LANG']['tl_content']['ch_preview']['0'] = "Fichero fuente";
$GLOBALS['TL_LANG']['tl_content']['ch_preview']['1'] = "Elige un fichero JPG o PNG que representará la primera escena del vídeo.";
$GLOBALS['TL_LANG']['tl_content']['movie_legend'] = "Ajustes del vídeo";
$GLOBALS['TL_LANG']['tl_content']['preview_legend'] = "Imagen de la escena inicial";
$GLOBALS['TL_LANG']['tl_content']['params_legend'] = "Parámetros";
 
?>
