<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/es/tl_ch_flowplayer.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.4 stable 
 * Spanisch translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Klaus Bogotz (klabog) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['title']['0'] = "Titulo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['title']['1'] = "Titulo de la lista reproductora";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['tstamp']['0'] = "Fecha modificada";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['tstamp']['1'] = "Fecha y hora de la ultima modificación";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['new']['0'] = "Lista reproductora nueva";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['new']['1'] = "Crea una nueva lista reproductora";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['edit']['0'] = "Edita la lista reproductora";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['edit']['1'] = "Edita la lista reproductora ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['copy']['0'] = "Duplica la lista reproductora";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['copy']['1'] = "Duplica la lista reproductora ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['delete']['0'] = "Borra la lista reproductora";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['delete']['1'] = "Borra la lista reproductora ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['show']['0'] = "Detalles de la lista reproductora";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['show']['1'] = "Detalles de la lista reproductora ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['title_legend'] = "Titulo";
 
?>
