<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/es/tl_module.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.4 stable 
 * Spanisch translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Klaus Bogotz (klabog) 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['ch_playlists']['0'] = "Lista reproductora";
$GLOBALS['TL_LANG']['tl_module']['ch_playlists']['1'] = "Elige la lista reproductora de los vídeos deseados.";
$GLOBALS['TL_LANG']['tl_module']['ch_autoplay']['0'] = "Reproducción automática";
$GLOBALS['TL_LANG']['tl_module']['ch_autoplay']['1'] = "Arranca el vídeo automáticamente cuando la página se carga";
$GLOBALS['TL_LANG']['tl_module']['ch_playersize']['0'] = "Anchura y altura";
$GLOBALS['TL_LANG']['tl_module']['ch_playersize']['1'] = "Anchura y altura del reproductor.";
 
?>
