<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/nl/default.php 
 * 
 * Contao extension: ch_flowplayer 0.0.4 stable 
 * Dutch translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Joeri Boudewijns (bojoer), bojoer 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['ch_flowplayer']['0'] = "Flowplayer Afspeellijsten";
$GLOBALS['TL_LANG']['MOD']['ch_flowplayer']['1'] = "Beheer Flowplayer video's en afspeellijsten";
$GLOBALS['TL_LANG']['CTE']['ch_flowplayer']['0'] = "Flowplayer Video";
$GLOBALS['TL_LANG']['CTE']['ch_flowplayer']['1'] = "Ebmed een video met Flowplayer";
$GLOBALS['TL_LANG']['ch_flowplayer']['error'] = "Video niet gevonden";
 
?>
