<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/nl/modules.php 
 * 
 * Contao extension: ch_flowplayer 0.0.4 stable 
 * Dutch translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Joeri Boudewijns (bojoer), bojoer 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['ch_flowplayer_reader']['0'] = "Flowplayer Lezer";
$GLOBALS['TL_LANG']['FMD']['ch_flowplayer_reader']['1'] = "embed een Flowplayer object dat verbonden is aan een afspeellijst";
$GLOBALS['TL_LANG']['FMD']['ch_flowplayer_list']['0'] = "Flowplayer Lijst";
$GLOBALS['TL_LANG']['FMD']['ch_flowplayer_list']['1'] = "genereert een lijst van videos van een afspeellijst";
 
?>
