<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/nl/tl_ch_flowplayer.php 
 * 
 * Contao extension: ch_flowplayer 0.0.4 stable 
 * Dutch translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Joeri Boudewijns (bojoer), bojoer 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['title']['1'] = "Afspeellijst Titel";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['tstamp']['0'] = "Datum laatste wijziging";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['tstamp']['1'] = "Datum en uur van laatste wijziging";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['new']['0'] = "Nieuwe Afspeellijst";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['new']['1'] = "Creëer een nieuwe afspeellijst";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['edit']['0'] = "Bewerk Afspeellijst";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['edit']['1'] = "Bewerk afspeellijst ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['copy']['0'] = "Dupliceer Afspeellijst";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['copy']['1'] = "Dupliceer afspeellijst ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['delete']['0'] = "Verwijder Afspeellijst";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['delete']['1'] = "Verwijder afspeellijst ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['show']['0'] = "Afspeellijst Details";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['show']['1'] = "Details van afspeellijst ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['title_legend'] = "Titel";
 
?>
