<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/nl/tl_ch_flowplayer_playlist.php 
 * 
 * Contao extension: ch_flowplayer 0.0.4 stable 
 * Dutch translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Joeri Boudewijns (bojoer), bojoer 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['title']['1'] = "Titel van de video";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['alias']['0'] = "Video alias";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['alias']['1'] = "De video alias is een unieke referentie die aangeroepen kan worden in plaats van het numerieke video ID.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['description']['0'] = "Omschrijving";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['description']['1'] = "Meer details over de video.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['movie']['0'] = "Bron bestand";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['movie']['1'] = "Selecteer een FLV, MP4 of SWF bestand";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['preview']['0'] = "Voorbekijken";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['preview']['1'] = "Afbeelding voor de film trailer";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['params']['0'] = "Parameter";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['params']['1'] = "Parameters volgens flowplayer.org die enkel impact mogen hebben op deze video. Het ingeven van parameters zal eender welke instelling, die hierboven werd gedefiniëerd, overschrijven. Zoals autoplay. Je kan ze hier opnieuw manueel toevoegen.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['published']['0'] = "Gepubliceerd";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['published']['1'] = "De video is gepubliceerd.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['addImage']['0'] = "Voeg een afbeelding toe.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['addImage']['1'] = "Voeg een afbeelding toe aan deze video.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['new']['0'] = "Nieuwe video.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['new']['1'] = "Creëer een nieuwe video.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['edit']['0'] = "Bewerk Video";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['edit']['1'] = "Bewerk video ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['copy']['0'] = "Dupliceer Video";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['copy']['1'] = "Dupliceer video ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['delete']['0'] = "Verwijder Video";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['delete']['1'] = "Verwijder video ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['show']['0'] = "Video Details";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['show']['1'] = "Details van video ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['title_legend'] = "Titel en Alias";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['movie_legend'] = "Video Instellingen";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['params_legend'] = "Parameter Instellingen";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['publish_legend'] = "Publicatie";
$GLOBALS['TL_LANG']['tl_style']['cut']['0'] = "Verplaats Video";
$GLOBALS['TL_LANG']['tl_style']['cut']['1'] = "Verplaats video ID %s";
$GLOBALS['TL_LANG']['tl_style']['pasteafter']['0'] = "Plak aan de top";
$GLOBALS['TL_LANG']['tl_style']['pasteafter']['1'] = "Plak achter video ID %s";
$GLOBALS['TL_LANG']['tl_style']['pastenew']['0'] = "Voeg nieuwe toe aan de top";
$GLOBALS['TL_LANG']['tl_style']['pastenew']['1'] = "Voeg nieuwe toe achter video ID %s";
 
?>
