<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/nl/tl_content.php 
 * 
 * Contao extension: ch_flowplayer 0.0.4 stable 
 * Dutch translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Joeri Boudewijns (bojoer), bojoer 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['ch_params']['0'] = "Parameter";
$GLOBALS['TL_LANG']['tl_content']['ch_params']['1'] = "Parameters volgens flowplayer.org die enkel impact mogen hebben op deze video. Het ingeven van parameters zal eender welke instelling, die hierboven werd gedefiniëerd, overschrijven. Zoals autoplay. Je kan ze hier opnieuw manueel toevoegen.";
$GLOBALS['TL_LANG']['tl_content']['ch_movie']['0'] = "Bron bestand";
$GLOBALS['TL_LANG']['tl_content']['ch_movie']['1'] = "Selecteer een FLV, MP4 of SWF bestand";
$GLOBALS['TL_LANG']['tl_content']['ch_playersize']['0'] = "Breedte en hoogte";
$GLOBALS['TL_LANG']['tl_content']['ch_playersize']['1'] = "De breedte en hoogte van de speler.";
$GLOBALS['TL_LANG']['tl_content']['ch_description']['0'] = "Omschrijving";
$GLOBALS['TL_LANG']['tl_content']['ch_description']['1'] = "Meer details over de video";
$GLOBALS['TL_LANG']['tl_content']['ch_autoplay']['0'] = "Automatisch afspelen";
$GLOBALS['TL_LANG']['tl_content']['ch_autoplay']['1'] = "Start de video automatisch wanneer de pagina geladen is.";
$GLOBALS['TL_LANG']['tl_content']['ch_preview']['0'] = "Bron bestand";
$GLOBALS['TL_LANG']['tl_content']['ch_preview']['1'] = "Kies een JPG of PNG bestand, welke getoond zal worden als eerste frame van de video.";
$GLOBALS['TL_LANG']['tl_content']['movie_legend'] = "Video instellingen";
$GLOBALS['TL_LANG']['tl_content']['preview_legend'] = "Initiële Frame Afbeelding";
$GLOBALS['TL_LANG']['tl_content']['params_legend'] = "Parameters";
 
?>
