<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/nl/tl_module.php 
 * 
 * Contao extension: ch_flowplayer 0.0.4 stable 
 * Dutch translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Joeri Boudewijns (bojoer), bojoer 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['ch_playlists']['0'] = "Afspeellijsten";
$GLOBALS['TL_LANG']['tl_module']['ch_playlists']['1'] = "Selecteer de afspeellijsten met de gewenste video's.";
$GLOBALS['TL_LANG']['tl_module']['ch_autoplay']['0'] = "Automatisch afspelen.";
$GLOBALS['TL_LANG']['tl_module']['ch_autoplay']['1'] = "Start de video automatisch wanneer de pagina geladen is.";
$GLOBALS['TL_LANG']['tl_module']['ch_playersize']['0'] = "Breedte en hoogte";
$GLOBALS['TL_LANG']['tl_module']['ch_playersize']['1'] = "De breedte en hoogte van de speler.";
 
?>
