<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/it/default.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.2 stable 
 * Italian translation file 
 * 
 * Copyright : 2009 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['ch_flowplayer']['0'] = "Video";
$GLOBALS['TL_LANG']['MOD']['ch_flowplayer']['1'] = "Questo modulo permette di gestisre filmati FLV con FlowPlayer";
$GLOBALS['TL_LANG']['CTE']['ch_flowplayer']['0'] = "Video";
$GLOBALS['TL_LANG']['CTE']['ch_flowplayer']['1'] = "Riprodurre filmati FLV con FlowPlayer";
$GLOBALS['TL_LANG']['ch_flowplayer']['error'] = "Filmato non trovato";
 
?>
