<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/it/modules.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.2 stable 
 * Italian translation file 
 * 
 * Copyright : 2009 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['ch_flowplayer_reader']['0'] = "FlowPlayer Reader";
$GLOBALS['TL_LANG']['FMD']['ch_flowplayer_reader']['1'] = "Con questo modulo è possibile riprodurre una playlist con FlowPlayer";
$GLOBALS['TL_LANG']['FMD']['ch_flowplayer_list']['0'] = "FlowPlayer playlist";
$GLOBALS['TL_LANG']['FMD']['ch_flowplayer_list']['1'] = "Questo modulo permette di riprodurre una\nplaylist con FlowPlayer";
 
?>
