<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/it/tl_ch_flowplayer_playlist.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.2 stable 
 * Italian translation file 
 * 
 * Copyright : 2009 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['title']['0'] = "Titolo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['title']['1'] = "Inserisci il titolo del filmato";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['alias']['0'] = "Alias del filmato";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['alias']['1'] = "L'alias è un riferimento univoco del filmato che può essere richiamato al posto del ID.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['description']['0'] = "Descrizione";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['description']['1'] = "Inserire una descrizione del filmato";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['movie']['0'] = "Filmato";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['movie']['1'] = "Seleziona un file in formasto FLV, MP4 o SWF";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['preview']['0'] = "Anteprima";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['preview']['1'] = "Immagine che mostra un'anteprima del filmato. Seleziona un file JPG o PNG";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['params']['0'] = "Parametri";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['params']['1'] = "Parametri compatibili con flowplayer.org da utilizzare esclusivamente per questo filmato";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['published']['0'] = "Pubblicato";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['published']['1'] = "Il filmato non sarà visibile finchè questa opzione non sarà selezionata";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['addImage']['0'] = "Immagine anteprima";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['addImage']['1'] = "Con questa opzione è possibile collegare ad ogni filmato un'immagine di anteprima che lo rappresenti.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['new']['0'] = "Nuovo Filmato";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['new']['1'] = "Aggiungi un nuovo Filmato";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['edit']['0'] = "Modifica del Filmato";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['edit']['1'] = "Modifica Filmato con ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['copy']['0'] = "Duplica Filmato";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['copy']['1'] = "Duplica Filmato ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['delete']['0'] = "Elimina Filmato";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['delete']['1'] = "Cancella Filmato ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['show']['0'] = "Dettagli del Filmato";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['show']['1'] = "Mostra dettagli del Filmato ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['title_legend'] = "Titolo e Alias";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['movie_legend'] = "Preferenze Filmato";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['params_legend'] = "Impostazione dei Parametri";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['publish_legend'] = "Pubblicazione";
 
$GLOBALS['TL_LANG']['tl_style']['cut']        = array('Move video', 'Move video ID %s');
$GLOBALS['TL_LANG']['tl_style']['pasteafter'] = array('Paste at the top', 'Paste after video ID %s');
$GLOBALS['TL_LANG']['tl_style']['pastenew']   = array('Add new at the top', 'Add new after video ID %s');

?>
