<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/it/tl_ch_flowplayer.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.2 stable 
 * Italian translation file 
 * 
 * Copyright : 2009 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['title']['0'] = "Titolo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['title']['1'] = "Inserire il titolo della Playlist";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['tstamp']['0'] = "Data di modifica";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['tstamp']['1'] = "Data e ora dell'ultima modifica";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['new']['0'] = "Nuova Playlist";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['new']['1'] = "Crea una nuova Playlist";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['edit']['0'] = "Modifica Playlist";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['edit']['1'] = "Modifica Playlist ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['copy']['0'] = "Duplica Playlist";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['copy']['1'] = "Duplica Playlist ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['delete']['0'] = "Elimina Playlist";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['delete']['1'] = "Elimina Playlist ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['show']['0'] = "Dettagli Playlist";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['show']['1'] = "Mostra dettagli della Playlist ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['title_legend'] = "Titolo";
 
?>
