<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/it/tl_content.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.2 stable 
 * Italian translation file 
 * 
 * Copyright : 2009 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['ch_params']['0'] = "Parametri";
$GLOBALS['TL_LANG']['tl_content']['ch_params']['1'] = "Parametri compatibili con flowplayer.org da utilizzare esclusivamente per questo filmato";
$GLOBALS['TL_LANG']['tl_content']['ch_movie']['0'] = "Filmato";
$GLOBALS['TL_LANG']['tl_content']['ch_movie']['1'] = "Seleziona un file in formasto FLV, MP4 o SWF";
$GLOBALS['TL_LANG']['tl_content']['ch_playersize']['0'] = "Larghezza ed altezza del filmato";
$GLOBALS['TL_LANG']['tl_content']['ch_playersize']['1'] = "Inserire larghezza ed altezza nella quale desideri venga visualizzato il filmato";
$GLOBALS['TL_LANG']['tl_content']['ch_description']['0'] = "Descrizione";
$GLOBALS['TL_LANG']['tl_content']['ch_description']['1'] = "Inserire una descrizione del filmato";
$GLOBALS['TL_LANG']['tl_content']['ch_autoplay']['0'] = "Autoplay";
$GLOBALS['TL_LANG']['tl_content']['ch_autoplay']['1'] = "Selezionare questa opzione se si desidera che il filmato si avvii automaticamente";
$GLOBALS['TL_LANG']['tl_content']['ch_preview']['0'] = "Sorgente file";
$GLOBALS['TL_LANG']['tl_content']['ch_preview']['1'] = "Con questa opzione è possibile collegare ad ogni filmato un'immagine di anteprima che lo rappresenti";
$GLOBALS['TL_LANG']['tl_content']['movie_legend'] = "Preferenze Filmato";
$GLOBALS['TL_LANG']['tl_content']['preview_legend'] = "Immagine anteprima";
$GLOBALS['TL_LANG']['tl_content']['params_legend'] = "Parametri";
 
?>
