<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/it/tl_module.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.2 stable 
 * Italian translation file 
 * 
 * Copyright : 2009 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.typolightcms.it 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['ch_playlists']['0'] = "Playlist";
$GLOBALS['TL_LANG']['tl_module']['ch_playlists']['1'] = "Seleziona la playlist che desideri visualizzare";
$GLOBALS['TL_LANG']['tl_module']['ch_autoplay']['0'] = "Autoplay";
$GLOBALS['TL_LANG']['tl_module']['ch_autoplay']['1'] = "Selezionare questa opzione se si desidera che il filmato si avvii automaticamente";
$GLOBALS['TL_LANG']['tl_module']['ch_playersize']['0'] = "Larghezza ed altezza del filmato";
$GLOBALS['TL_LANG']['tl_module']['ch_playersize']['1'] = "Inserire larghezza ed altezza nella quale desideri venga visualizzato il filmato";
 
?>
