<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/fr/default.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.4 stable 
 * French translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['ch_flowplayer']['0'] = "Playlists FlowPlayer";
$GLOBALS['TL_LANG']['MOD']['ch_flowplayer']['1'] = "Gérer les vidéo et les listes de lecture FlowPlayer";
$GLOBALS['TL_LANG']['CTE']['ch_flowplayer']['0'] = "Vidéo FlowPlayer";
$GLOBALS['TL_LANG']['CTE']['ch_flowplayer']['1'] = "Embarquer une vidéo avec FlowPlayer";
$GLOBALS['TL_LANG']['ch_flowplayer']['error'] = "Vidéo non trouvé.";
 
?>
