<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/fr/modules.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.4 stable 
 * French translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['ch_flowplayer_reader']['0'] = "Lecteur FlowPlayer";
$GLOBALS['TL_LANG']['FMD']['ch_flowplayer_reader']['1'] = "Embarquer un objet FlowPlayer lié à une liste de lecture";
$GLOBALS['TL_LANG']['FMD']['ch_flowplayer_list']['0'] = "Liste FlowPlayer";
$GLOBALS['TL_LANG']['FMD']['ch_flowplayer_list']['1'] = "Génere une liste de vidéos à partir d'une liste de lecture";
 
?>
