<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/fr/tl_ch_flowplayer.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.4 stable 
 * French translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['title']['1'] = "Titre liste de lecture";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['tstamp']['0'] = "Date de modification";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['tstamp']['1'] = "Date et heure de dernière modification";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['new']['0'] = "Nouvelle liste de lecture";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['new']['1'] = "Créer une nouvelle liste de lecture";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['edit']['0'] = "Editer la liste de lecture";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['edit']['1'] = "Editer la liste de lecture ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['copy']['0'] = "Dupliquer la liste de lecture";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['copy']['1'] = "Dupliquer la liste de lecture ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['delete']['0'] = "Effacer la liste de lecture";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['delete']['1'] = "Effacer la liste de lecture ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['show']['0'] = "Détails de liste de lecture";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['show']['1'] = "Détails de la liste de lecture ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer']['title_legend'] = "Titre";
 
?>
