<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/fr/tl_ch_flowplayer_playlist.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.4 stable 
 * French translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['title']['1'] = "Titre de la vidéo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['alias']['0'] = "Alias de la vidéo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['alias']['1'] = "L'alias de la vidéo est une référence unique qui peut être appelé à la de l'identifiant numérique (ID) de la vidéo.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['description']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['description']['1'] = "Plus de détails à propos de la vidéo.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['movie']['0'] = "Fichier source";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['movie']['1'] = "Sélectionnez un fichier FLV, MP4 ou SWF";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['preview']['0'] = "Aperçu";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['preview']['1'] = "Image pour la couverture de vidéo. Veuillez choisir un fichier JPG ou PNG.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['params']['0'] = "Paramètres";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['params']['1'] = "Paramètres en relation avec flowplayer.org qui doivent uniquement s'appliquer à cette vidéo. Les paramètres saisis ici surchargeront les paramètres ayant été entrés en amont, comme la lecture auto. Vous devez le re-ajouter manuellement.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['published']['0'] = "Publié";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['published']['1'] = "Cette vidéo est publié.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['addImage']['0'] = "Ajouter une image";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['addImage']['1'] = "Ajoute une image à la vidéo.";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['new']['0'] = "Nouvelle vidéo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['new']['1'] = "Créer une nouvelle vidéo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['edit']['0'] = "Editer vidéo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['edit']['1'] = "Editer la vidéo ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['copy']['0'] = "Dupliquer vidéo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['copy']['1'] = "Dupliquer la vidéo ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['delete']['0'] = "Effacer vidéo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['delete']['1'] = "Effacer la vidéo ID %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['show']['0'] = "Détails vidéo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['show']['1'] = "Détails de la vidéo %s";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['title_legend'] = "Titre et alias";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['movie_legend'] = "Paramètres vidéo";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['params_legend'] = "Paramétrage";
$GLOBALS['TL_LANG']['tl_ch_flowplayer_playlist']['publish_legend'] = "Publication";
$GLOBALS['TL_LANG']['tl_style']['cut']['0'] = "Déplacer vidéo";
$GLOBALS['TL_LANG']['tl_style']['cut']['1'] = "Déplacer la vidéo ID %s";
$GLOBALS['TL_LANG']['tl_style']['pasteafter']['0'] = "Coller tout en haut";
$GLOBALS['TL_LANG']['tl_style']['pasteafter']['1'] = "Coller après la vidéo ID %s";
$GLOBALS['TL_LANG']['tl_style']['pastenew']['0'] = "Ajouter tout en haut";
$GLOBALS['TL_LANG']['tl_style']['pastenew']['1'] = "Ajouter après la vidéo ID %s";
 
?>
