<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/fr/tl_content.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.4 stable 
 * French translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['ch_params']['0'] = "Paramètres";
$GLOBALS['TL_LANG']['tl_content']['ch_params']['1'] = "Paramètres en relation avec flowplayer.org qui doivent uniquement s'appliquer à cette vidéo. Les paramètres saisis ici surchargeront les paramètres ayant été entrés en amont, comme la lecture auto. Vous devez le re-ajouter manuellement.";
$GLOBALS['TL_LANG']['tl_content']['ch_movie']['0'] = "Fichier source";
$GLOBALS['TL_LANG']['tl_content']['ch_movie']['1'] = "Sélectionnez un fichier FLV, MP4 ou SWF";
$GLOBALS['TL_LANG']['tl_content']['ch_playersize']['0'] = "Largeur et hauteur";
$GLOBALS['TL_LANG']['tl_content']['ch_playersize']['1'] = "La largeur et la hauteur du lecteur.";
$GLOBALS['TL_LANG']['tl_content']['ch_description']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_content']['ch_description']['1'] = "Plus de détails à propos de la vidéo";
$GLOBALS['TL_LANG']['tl_content']['ch_autoplay']['0'] = "Lecture auto";
$GLOBALS['TL_LANG']['tl_content']['ch_autoplay']['1'] = "Lancer la lecture dès que la page est chargée";
$GLOBALS['TL_LANG']['tl_content']['ch_preview']['0'] = "Fichier source";
$GLOBALS['TL_LANG']['tl_content']['ch_preview']['1'] = "Choisissez un fichier JPG ou PNG, qui sera affiché comme première image de la vidéo.";
$GLOBALS['TL_LANG']['tl_content']['movie_legend'] = "Paramètres vidéo";
$GLOBALS['TL_LANG']['tl_content']['preview_legend'] = "Image initiale";
$GLOBALS['TL_LANG']['tl_content']['params_legend'] = "Paramètres";
 
?>
