<?php
/**
 * TL_ROOT/system/modules/ch_flowplayer/languages/fr/tl_module.php 
 * 
 * TYPOlight extension: ch_flowplayer 0.0.4 stable 
 * French translation file 
 * 
 * Copyright : 2009-2010 de la Haye Kommunikationsdesign 
 * License   : LGPL 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['ch_playlists']['0'] = "Listes de lecture";
$GLOBALS['TL_LANG']['tl_module']['ch_playlists']['1'] = "Sélectionnez les listes de lecture avec les vidéos voulues.";
$GLOBALS['TL_LANG']['tl_module']['ch_autoplay']['0'] = "Lecture auto";
$GLOBALS['TL_LANG']['tl_module']['ch_autoplay']['1'] = "Lancer la lecture dès que la page est chargée.";
$GLOBALS['TL_LANG']['tl_module']['ch_playersize']['0'] = "Largeur et hauteur";
$GLOBALS['TL_LANG']['tl_module']['ch_playersize']['1'] = "La largeur et la hauteur du lecteur.";
 
?>
